name: Push (master)
on:
  push:
    branches: ["master"]
jobs:
  deploy-pages:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install poetry
        uses: Gr1N/setup-poetry@v8

      - name: Build package
        run: |
          poetry build
          cp dist/*.whl web/
          mv web/*.whl web/upk2esphome.whl

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: web/
          target-folder: /
          force: true
